### ISSUE TITLE
RN02 - Aumentar a cobertura de testes do projeto

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2023-1-PUMA-Doc#19]
Conforme a implementação da ORM, é necessário aumentar a cobertura de testes unitários nos serviços.

- [x] User Service
- [x] Project Service
- [x] Api Gateway

**Comment by abner423** [comment]
Para complementar, foi percebido a necessidade da refatoração dos testes da aplicação, visto que tinha uma pasta Legacy e os testes que tinham eram testes de integração que não estavam testando lógica de nada, além de envolver uma complexidade muito grande com necessidade de subir um Docker e etc. Pelo fato de trocarmos a implementação para uso de ORM, notamos que testar se o framework está ou não performance como deveria na base, não faria mais sentido, visto que é um framework de pleno uso por várias empresas e projetos/
